let _metadata = createMetadata({
      "Go Tell Aunt Rhody - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "A Loving Message - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "On The Road - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Atmosphere Swamp Encounter - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Lost Memories - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Sinking Feeling - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Into Madness - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Kill Or Be Killed - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Haunted House - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Back For More - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Love To Death - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Welcome To The Family - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Dinner Time - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Out Of Sight - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Out In The Open - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Garage - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Main Hall - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "A Curious Light - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Hide And Seek - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Daddy's Back - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Molded I - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Tearing At The Flesh - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Claws Of Death - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Into The Night - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Saferoom - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Atmosphere -The Nest- - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Brief Reunion - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Escaping The Pit - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Unholy Shrine - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Keeper Of The Greenhouse I - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Keeper Of The Greenhouse II - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "The Forbidden Room - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Tatari - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Molded II - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Bad Boy Games - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "White Room - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Sacrifice By The Sewer Gatorz - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Apprehension - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "So Close Yet So Far - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Face To Face - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "The Beast - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Not Over Yet - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "The Choice -Love- - Resident Evil 7 Biohazard": [2017, "Resident Evil 7 Biohazard"],
      "Ada's Theme - Resident Evil 2": [1998, "Resident Evil 2"],
      "Above The Blood Pool - Resident Evil 2": [1998, "Resident Evil 2"],
      "And After That - Resident Evil 2": [1998, "Resident Evil 2"],
      "Annette's Recollection - Resident Evil 2": [1998, "Resident Evil 2"],
      "Credit Line of Whole Staff - Resident Evil 2": [1998, "Resident Evil 2"],
      "Soundtrack Credits - Resident Evil 2": [1998, "Resident Evil 2"],
      "Dawn Never Fails to Come - Resident Evil 2": [1998, "Resident Evil 2"],
      "Destined to be Malformed - Resident Evil 2": [1998, "Resident Evil 2"],
      "Dropping Again - Resident Evil 2": [1998, "Resident Evil 2"],
      "Drove the Passengers to be the Living Dead - Resident Evil 2": [1998, "Resident Evil 2"],
      "Embryo Into its Cradle - Resident Evil 2": [1998, "Resident Evil 2"],
      "Falling Victim to ex Neighbors - Resident Evil 2": [1998, "Resident Evil 2"],
      "Fearful is no Word for it - Resident Evil 2": [1998, "Resident Evil 2"],
      "Find the Final One - Resident Evil 2": [1998, "Resident Evil 2"],
      "Good Bye Leon - Resident Evil 2": [1998, "Resident Evil 2"],
      "Heads Up - Resident Evil 2": [1998, "Resident Evil 2"],
      "His Final Scoop - Resident Evil 2": [1998, "Resident Evil 2"],
      "Hope Against Hope - Resident Evil 2": [1998, "Resident Evil 2"],
      "Is Ada Spy - Resident Evil 2": [1998, "Resident Evil 2"],
        "It Is After You - Resident Evil 2": [1998, "Resident Evil 2"],
      "Left Alone - Resident Evil 2": [1998, "Resident Evil 2"],
      "Leon With Claire - Resident Evil 2": [1998, "Resident Evil 2"],
      "Like A Shadow - Resident Evil 2": [1998, "Resident Evil 2"],
      "Long And Gloomy Underground Passage - Resident Evil 2": [1998, "Resident Evil 2"],
      "Madness Under The Mask - Resident Evil 2": [1998, "Resident Evil 2"],
      "Maximize Your Survival Instinct - Resident Evil 2": [1998, "Resident Evil 2"],
      "Mission Accomplished - Resident Evil 2": [1998, "Resident Evil 2"],
      "Mother - Resident Evil 2": [1998, "Resident Evil 2"],
      "Normal End Title - Resident Evil 2": [1998, "Resident Evil 2"],
      "Nothing More To Do Here - Resident Evil 2 1998": [1998, "Resident Evil 2"],
      "Now In Two Pieces - Resident Evil 2": [1998, "Resident Evil 2"],
      "One More Kiss - Resident Evil 2": [1998, "Resident Evil 2"],
      "Prologue - Resident Evil 2": [1998, "Resident Evil 2"],
      "Raccoon City  - Resident Evil 2": [1998, "Resident Evil 2"],
      "Screaming Target - Resident Evil 2": [1998, "Resident Evil 2"],
      "Secure Place - Resident Evil 2": [1998, "Resident Evil 2"],
      "Set About The Mission - Resident Evil 2": [1998, "Resident Evil 2"],
      "Sherry's Theme - Resident Evil 2": [1998, "Resident Evil 2"],
      "Special End Title - Resident Evil 2": [1998, "Resident Evil 2"],
      "T A - Resident Evil 2": [1998, "Resident Evil 2"],
      "T B - Resident Evil 2": [1998, "Resident Evil 2"],
      "The Basement Of Police Station - Resident Evil 2": [1998, "Resident Evil 2"],
      "The Beginning Of Story - Resident Evil 2": [1998, "Resident Evil 2"],
      "The Build Up Of Suspense - Resident Evil 2": [1998, "Resident Evil 2"],
      "The Daredevil Four - Resident Evil 2": [1998, "Resident Evil 2"],
      "The Evil Eye - Resident Evil 2": [1998, "Resident Evil 2"],
      "The First Floor - Resident Evil 2": [1998, "Resident Evil 2"],
      "The First Malformation Of G  - Resident Evil 2": [1998, "Resident Evil 2"],
      "The Front Hall - Resident Evil 2": [1998, "Resident Evil 2"],
      "The Gigantic Alligator - Resident Evil 2": [1998, "Resident Evil 2"],
      "The Library - Resident Evil 2": [1998, "Resident Evil 2"],
      "The Marshalling Yard 2 - Resident Evil 2": [1998, "Resident Evil 2"],
      "The Marshalling Yard  - Resident Evil 2": [1998, "Resident Evil 2"],
      "The Second Floor- Resident Evil 2": [1998, "Resident Evil 2"],
      "The Second Malformation Of G - Resident Evil 2": [1998, "Resident Evil 2"],
      "The Shadow Is Gone - Resident Evil 2": [1998, "Resident Evil 2"],
      "The Third Malformation Of G - Resident Evil 2": [1998, "Resident Evil 2"],
      "The Underground Laboratory - Resident Evil 2": [1998, "Resident Evil 2"],
      "This Is My Nest - Resident Evil 2": [1998, "Resident Evil 2"],
      "To Another Nightmare - Resident Evil 2": [1998, "Resident Evil 2"],
      "Under Cover Of Darkness - Resident Evil 2": [1998, "Resident Evil 2"],
      "Wandering Alone - Resident Evil 2": [1998, "Resident Evil 2"],
      "We Will Never Die - Resident Evil 2": [1998, "Resident Evil 2"],
      "Weapons Don't Give Us Relief - Resident Evil 2": [1998, "Resident Evil 2"],
      "Who's That Lady - Resident Evil 2": [1998, "Resident Evil 2"],
      "Women Squaring Off - Resident Evil 2": [1998, "Resident Evil 2"],
      "Wreckage Of The Mad Experiment - Resident Evil 2": [1998, "Resident Evil 2"],
      "Your Mission - Resident Evil 2": [1998, "Resident Evil 2"],
       "Title Movie - Resident Evil 5": [2009, "Resident Evil 5"],
      "Opening Chris's Arrival- Resident Evil 5": [2009, "Resident Evil 5"],
      "Item Box - Resident Evil 5": [2009, "Resident Evil 5"],
      "New Fear - Resident Evil 5": [2009, "Resident Evil 5"],
      "Magic Act - Resident Evil 5": [2009, "Resident Evil 5"],
      "The Butcher - Resident Evil 5": [2009, "Resident Evil 5"],
      "The Town - Resident Evil 5": [2009, "Resident Evil 5"],
      "First Encounter - Resident Evil 5": [2009, "Resident Evil 5"],
      "Manjini I - Resident Evil 5": [2009, "Resident Evil 5"],
      "Hospitality - Resident Evil 5": [2009, "Resident Evil 5"],
      "Manjini II - Resident Evil 5": [2009, "Resident Evil 5"],
      "Game Over - Resident Evil 5": [2009, "Resident Evil 5"],
      "Damsel in Distress - Resident Evil 5": [2009, "Resident Evil 5"],
      "Manjini III - Resident Evil 5": [2009, "Resident Evil 5"],
      "A Piece of the Puzzle - Resident Evil 5": [2009, "Resident Evil 5"],
      "Unidentified Threat - Resident Evil 5": [2009, "Resident Evil 5"],
      "An Emergency - Resident Evil 5": [2009, "Resident Evil 5"],
      "The Storage Facility - Resident Evil 5": [2009, "Resident Evil 5"],
      "Result - Resident Evil 5": [2009, "Resident Evil 5"],
      "The Ripper - Resident Evil 5": [2009, "Resident Evil 5"],
      "Executioner - Resident Evil 5": [2009, "Resident Evil 5"],
      "The Crisis ~Reinforcements Arrive - Resident Evil 5": [2009, "Resident Evil 5"],
      "Voice of The Darkness - Resident Evil 5": [2009, "Resident Evil 5"],
      "Terror from Above - Resident Evil 5": [2009, "Resident Evil 5"],
      "Flying Nightmare - Resident Evil 5": [2009, "Resident Evil 5"],
      "Pursuer and The Pursued - Resident Evil 5": [2009, "Resident Evil 5"],
      "Shaking off The Majini - Resident Evil 5": [2009, "Resident Evil 5"],
      "Grand Resurgence - Resident Evil 5": [2009, "Resident Evil 5"],
      "Burning With Anger - Resident Evil 5": [2009, "Resident Evil 5"],
      "Delta Team's Distress ~New Decision - Resident Evil 5": [2009, "Resident Evil 5"],
      "Shadows of the Past - Resident Evil 5": [2009, "Resident Evil 5"],
      "Eerie Stillness - Resident Evil 5": [2009, "Resident Evil 5"],
      "Majini IV - Resident Evil 5": [2009, "Resident Evil 5"],
      "Majini V - Resident Evil 5": [2009, "Resident Evil 5"],
      "Unite but - Resident Evil 5": [2009, "Resident Evil 5"],
      "Too Late - Resident Evil 5": [2009, "Resident Evil 5"],
      "Get Out! - Resident Evil 5": [2009, "Resident Evil 5"],
      "Majini's Trap I - Resident Evil 5": [2009, "Resident Evil 5"],
      "The Patrol Boat - Resident Evil 5": [2009, "Resident Evil 5"],
      "Evil Mutation - Resident Evil 5": [2009, "Resident Evil 5"],
      "A New Clue - Resident Evil 5": [2009, "Resident Evil 5"],
      "Ancient Noise - Resident Evil 5": [2009, "Resident Evil 5"],
      "Majini VI - Resident Evil 5": [2009, "Resident Evil 5"],
      "Majini's Trap II - Resident Evil 5": [2009, "Resident Evil 5"],
      "Excella and Wesker - Resident Evil 5": [2009, "Resident Evil 5"],
      "Underground Garden - Resident Evil 5": [2009, "Resident Evil 5"],
      "The Claw - Resident Evil 5": [2009, "Resident Evil 5"],
      "Huge Facility ~And then - Resident Evil 5": [2009, "Resident Evil 5"],
      "Gigantic Attack - Resident Evil 5": [2009, "Resident Evil 5"],
      "The Enigma - Resident Evil 5": [2009, "Resident Evil 5"],
      "Majini VII - Resident Evil 5": [2009, "Resident Evil 5"],
      "Haze of Horror - Resident Evil 5 ": [2009, "Resident Evil 5"],
      "OROBOROS - Resident Evil 5": [2009, "Resident Evil 5"],
      "The Mask - Resident Evil 5": [2009, "Resident Evil 5"],
      "Two on Two - Resident Evil 5": [2009, "Resident Evil 5"],
      "Old Friends, New Enemies - Resident Evil 5": [2009, "Resident Evil 5"],
      "Sad but true - Resident Evil 5": [2009, "Resident Evil 5"],
      "Trust - Resident Evil 5": [2009, "Resident Evil 5"],
      "The Tanker - Resident Evil 5": [2009, "Resident Evil 5"],
      "Majini VIII - Resident Evil 5": [2009, "Resident Evil 5"],
      "Shot OR Death - Resident Evil 5": [2009, "Resident Evil 5"],
      "A New Nightmare Begins - Resident Evil 5": [2009, "Resident Evil 5"],
      "Fragment of Fears - Resident Evil 5": [2009, "Resident Evil 5"],
      "The Sign - Resident Evil 5": [2009, "Resident Evil 5"],
      "A Big Despair - Resident Evil 5": [2009, "Resident Evil 5"],
      "Message - Resident Evil 5": [2009, "Resident Evil 5"],
      "Majini IX ~In Flames - Resident Evil 5": [2009, "Resident Evil 5"],
      "Rematch - Resident Evil 5": [2009, "Resident Evil 5"],
      "Wind Of Madness - Resident Evil 5": [2009, "Resident Evil 5"],
      "The Vulnerability - Resident Evil 5": [2009, "Resident Evil 5"],
      "Sky~High Skirmish - Resident Evil 5": [2009, "Resident Evil 5"],
      "The Final Curtain - Resident Evil 5": [2009, "Resident Evil 5"],
      "Deep Ambition - Resident Evil 5": [2009, "Resident Evil 5"],
      "Striker - Resident Evil 5": [2009, "Resident Evil 5"],
      "Homeward Bound! - Resident Evil 5": [2009, "Resident Evil 5"],
      "Pray ~Theme Song - Resident Evil 5": [2009, "Resident Evil 5"],
      "Plan of Uroboros - Resident Evil 5": [2009, "Resident Evil 5"],
      "Menu - Resident Evil 5": [2009, "Resident Evil 5"],
      "Viewer - Resident Evil 5": [2009, "Resident Evil 5"],
      "Colors - Resident Evil 5": [2009, "Resident Evil 5"],
      "Assault Fire - Resident Evil 5": [2009, "Resident Evil 5"],
      "Dreamy Loops - Resident Evil 5": [2009, "Resident Evil 5"],
      "On The Bass - Resident Evil 5": [2009, "Resident Evil 5"],
      "Rust in Summer 2008 - Resident Evil 5 ": [2009, "Resident Evil 5"],
      "KILLERS - Resident Evil 5": [2009, "Resident Evil 5"],
      "Do You Challenge Again - Resident Evil 5": [2009, "Resident Evil 5"],
      "Clone Awake - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "The Ditch - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "Alice Ride - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "Dog Attack - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "To the Hive - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "Flysolated - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "Convoy - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "Motel Closet - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "Dexterity - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "Perimeter Fire - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "Telepathic Sense - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "Desert Walk - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "Birds Attack - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "Choose Sides - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "Carlos Hug - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "Positive Id - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "For Alaska - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "New Orders - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "Vegas Journal - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "Container - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "Open Box - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "Losing Texan - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "To Tent - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "Tentacles - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "Carlos Plan - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "Tanker Trunk - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "Others Gone - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "Elevator - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "Your Blood - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "Clone Bubble - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "Alice Pic - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "Isaacs Dead - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "Laser Tunnel - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
      "New Headquarters - Resident Evil: Extinction": [2007, "Resident Evil: Extinction"],
  "Operation - Resident Evil Vendetta": [2017, "Resident Evil: Vendetta"],
"The Search - Resident Evil Vendetta": [2017, "Resident Evil: Vendetta"],
"Zack - Resident Evil Vendetta": [2017, "Resident Evil: Vendetta"],
"Retreat - Resident Evil Vendetta": [2017, "Resident Evil: Vendetta"],
"Cathy - Resident Evil Vendetta": [2017, "Resident Evil: Vendetta"],
"Vendetta ~ Main Title - Resident Evil Vendetta": [2017, "Resident Evil: Vendetta"],
"Arias ~ Lament - Resident Evil Vendetta": [2017, "Resident Evil: Vendetta"],
"Rebecca's Research - Resident Evil Vendetta": [2017, "Resident Evil: Vendetta"],
"Gas - Resident Evil Vendetta": [2017, "Resident Evil: Vendetta"],
"Infected - Resident Evil Vendetta": [2017, "Resident Evil: Vendetta"],
"Death Merchant - Resident Evil Vendetta": [2017, "Resident Evil: Vendetta"],
"Rocky Mountains - Resident Evil Vendetta": [2017, "Resident Evil: Vendetta"],
"Arias ~ Order - Resident Evil Vendetta": [2017, "Resident Evil: Vendetta"],
"Chris and Leon ~ Alike - Resident Evil Vendetta": [2017, "Resident Evil: Vendetta"],
"My Blood - Resident Evil Vendetta": [2017, "Resident Evil: Vendetta"],
"Patricio - Resident Evil Vendetta": [2017, "Resident Evil: Vendetta"],
"Abduction - Resident Evil Vendetta": [2017, "Resident Evil: Vendetta"],
"Animality Virus - Resident Evil Vendetta": [2017, "Resident Evil: Vendetta"],
"Meet Sarah - Resident Evil Vendetta": [2017, "Resident Evil: Vendetta"],
"Manhattan - Resident Evil Vendetta": [2017, "Resident Evil: Vendetta"],
"Cerberus - Resident Evil Vendetta": [2017, "Resident Evil: Vendetta"],
"Chris and Leon ~ Hideout  - Resident Evil Vendetta": [2017, "Resident Evil: Vendetta"],
"World in Flame - Resident Evil Vendetta": [2017, "Resident Evil: Vendetta"],
"Diego - Resident Evil Vendetta": [2017, "Resident Evil: Vendetta"],
"Extreme Battle - Resident Evil Vendetta": [2017, "Resident Evil: Vendetta"],
"Unleash It! - Resident Evil Vendetta": [2017, "Resident Evil: Vendetta"],
"Ariego - Resident Evil Vendetta": [2017, "Resident Evil: Vendetta"],
"The Final Stage - Resident Evil Vendetta": [2017, "Resident Evil: Vendetta"],
"Vaccine - Resident Evil Vendetta": [2017, "Resident Evil: Vendetta"],
"Vendetta ~ End Title - Resident Evil Vendetta": [2017, "Resident Evil: Vendetta"],
  "Abrupt Gunshots - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Against the Chopper - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"All Dressed Up - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"All of a Sudden - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Almost There - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Bring Back her Consciousness - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Cable Car Crash - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Carlos' Theme - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Choose the Best One - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"CM - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Cold Sweat - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Complete Rest - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Defiant Behavior - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Deservedly Death - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Don't Come Any Closer! - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Don't Lose Courage - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Earthquake - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Emergency Level D  - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Escape to Ectasy - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Escape Together - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Euthanasia of Racoon City - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Ever After - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Four Minutes Before the Treatment - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Free Falling - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Free From Fear - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Freedom Obtained - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"From Relief to Terror - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Hellish Agony - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Her Determination - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Hero Time - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Imminent Slaughter - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Impending Danger - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Is There a Way Out - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Meeting Brad - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Menacing Nemesis - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Missile Approaching - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Mysterious Orgel (Correct) - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Mysterious Orgel (Wrong) - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Nemesis Again - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Nemesis Doesn't Give Up  - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Nemesis Final Metamorphosis - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Nemesis' Theme - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Never Give up the Escape - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Nicholai's Theme - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"No Rest for the Wicked - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Nothing but a Pawn - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Ominous Presentiment - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Option Screen - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Pride and Valor - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Quick and Fast Relief - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Resurrection - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Reward and Results - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Staffs and Credits - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"The Beginning of Nightmare - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"The City of Ruin - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"The City Without Hope - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"The Clock Tower - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"The Disguised Plant - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"The Doomed City - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"The Grave Digger - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"The Great Novelist - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"The Hospital - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"The Last Argument - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"The Last Decision - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"The Last Escape - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"The Opening - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"The Park - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"The Second Chopper - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"The Worst Scenario - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Title Calling - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Traitor - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Treated to Resurrect - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Unfortunate Event - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Unstoppable Nemesis - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Valediction - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Watch Your Back - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Zombies Trespassing - Resident Evil 3 Nemesis": [1999, "Resident Evil 3: Nemesis"],
"Slide Projector - Resident Evil": [1996, "Resident Evil"],
"Snake Battle - Resident Evil": [1996, "Resident Evil"],
"Still Dawn - Resident Evil": [1996, "Resident Evil"],
"Sudden Attack - Resident Evil": [1996, "Resident Evil"],
"The Guardhouse - Resident Evil": [1996, "Resident Evil"],
"The Triggering System - Resident Evil": [1996, "Resident Evil"],
"The Underground - Resident Evil": [1996, "Resident Evil"],
"Third Floor of Laboratory - Resident Evil": [1996, "Resident Evil"],
"Tyrant Again - Resident Evil": [1996, "Resident Evil"],
"Tyrant Breaking Loose - Resident Evil": [1996, "Resident Evil"],
"Wesker is Found - Resident Evil": [1996, "Resident Evil"],
"Wesker's Theme - Resident Evil": [1996, "Resident Evil"],
"Yawn's Theme - Resident Evil": [1996, "Resident Evil"],
"After Rock Attack - Resident Evil": [1996, "Resident Evil"],
"Barry in Danger - Resident Evil": [1996, "Resident Evil"],
"Barry in Question - Resident Evil": [1996, "Resident Evil"],
"Barry Leaves the Guardhouse - Resident Evil": [1996, "Resident Evil"],
"Barry's Conversation - Resident Evil": [1996, "Resident Evil"],
"Barry's Death - Resident Evil": [1996, "Resident Evil"],
"Barry's Revenge - Resident Evil": [1996, "Resident Evil"],
"Battle Mode ~ Sega Saturn Only - Resident Evil": [1996, "Resident Evil"],
"Battle Mode Complete - Resident Evil": [1996, "Resident Evil"],
"Battle Mode Results  - Resident Evil": [1996, "Resident Evil"],
"Black Tiger  - Resident Evil": [1996, "Resident Evil"],
"Captured by Plant 42 - Resident Evil": [1996, "Resident Evil"],
"Complete Picture Puzzle - Resident Evil": [1996, "Resident Evil"],
"Death Trap - Resident Evil": [1996, "Resident Evil"],
"Dissappearance - Resident Evil": [1996, "Resident Evil"],
"First Floor Mansion - Resident Evil": [1996, "Resident Evil"],
"First Floor Mansion ~ Again - Resident Evil": [1996, "Resident Evil"],
"Forest is Dead - Resident Evil": [1996, "Resident Evil"],
"Guardhouse Basement - Resident Evil": [1996, "Resident Evil"],
"Mansion Basement - Resident Evil": [1996, "Resident Evil"],
"Meeting Rebecca - Resident Evil": [1996, "Resident Evil"],
"Moonlight Sonata - Resident Evil": [1996, "Resident Evil"],
"More Rooms - Resident Evil": [1996, "Resident Evil"],
"Piano Frenzy - Resident Evil": [1996, "Resident Evil"],
"Plant 42 - Resident Evil": [1996, "Resident Evil"],
"Plant 42 Battle - Resident Evil": [1996, "Resident Evil"],
"Poison Takes Richard - Resident Evil": [1996, "Resident Evil"],
"Rebecca's Death - Resident Evil": [1996, "Resident Evil"],
"Rebecca's in Danger - Resident Evil": [1996, "Resident Evil"],
"Rebecca's Safe in the Medical Room - Resident Evil": [1996, "Resident Evil"],
"Rescued Rebecca - Resident Evil": [1996, "Resident Evil"],
"Researcher's Will - Resident Evil": [1996, "Resident Evil"],
"Richard Found Dead - Resident Evil": [1996, "Resident Evil"],
"Richard's Crisis - Resident Evil": [1996, "Resident Evil"],
"Save Room - Resident Evil": [1996, "Resident Evil"],
"Saving Rebecca - Resident Evil": [1996, "Resident Evil"],
"Second Floor Mansion - Resident Evil": [1996, "Resident Evil"],
"Second Floor Mansion ~ Again - Resident Evil": [1996, "Resident Evil"],
  "Entrance to the Labratory - Resident Evil": [1996, "Resident Evil"],
"First Contact - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Here Comes the Knight - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Opening Claire - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"A Moment of Relief - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"A State of Emergency - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"As You Wish - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Ashford's Music Box - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"At Last - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Awesome Powers - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Bad Way or Bad Way - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Berceuse - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Blanc - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Claws of Doom - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Confrontation - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Crash - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Curiosity - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Death Siege - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Deja Vu - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Divided - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Doze - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"End Credits - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"End Credits (Dreamcast Version) - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Entrapment - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Father - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Final Weapon - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"For S.T.A.R.S. - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Fortress of Ants - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Getting Out - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Go With the Digger - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Greetings - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Here They Come - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Hot Rescue - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"I Need to Know - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Incoming - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Induction - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Infants - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Intrigue - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Invincible - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"It's Back - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Lachrymal - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Love - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Midnight Sun - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Murderous Eyes - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"New Battle - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Not Alexia - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Not Steve - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Once Again  - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"One Man Show  - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Opening Chris  - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Other Side of Glass - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Pandora's Box - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Piano Roll - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Prologue - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Pulsating Right Arm - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Putrid Smell - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"R.I.P. Rodrigo - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Rasen - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Resonance of Blood - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Resurrection - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Revenge - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Sardonic Smile - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Set Free - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Silence of the Air - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Steve's Strafe - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Still Alive - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Subzero - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"T Veronica - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Target Locked - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"The Code's Veronica - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"The Confined IT - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"The Ending of the Beginning - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"The Movie - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"The Palace of Insane - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"The Resurrection of Alexia - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"The Secret Door - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"The Suspended Doll - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"The Theme of Alexia Type 1 - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"The Theme of Alexia Type 2 - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"The Theme of Nosferatu - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"The Theme of Tyrant 3 Version A - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"The Theme of Tyrant 3 Version B - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Through the Scope - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Thrown Into Despair - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"To Antartica - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Transformation - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Velocity - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"You Think You're Safe Now - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"You Want It - Resident Evil Code Veronica": [2000, "Resident Evil Code Veronica"],
"Main Hall X - Resident Evil Gaiden": [2001, "Resident Evil Gaiden"],
"Submarine - Resident Evil Gaiden": [2001, "Resident Evil Gaiden"],
"Restaurant X - Resident Evil Gaiden": [2001, "Resident Evil Gaiden"],
"Class Cabin X - Resident Evil Gaiden": [2001, "Resident Evil Gaiden"],
"Battle - Resident Evil Gaiden": [2001, "Resident Evil Gaiden"],
"Title - Resident Evil Gaiden": [2001, "Resident Evil Gaiden"],
"Prologue - Resident Evil Gaiden": [2001, "Resident Evil Gaiden"],
"Side Deck - Resident Evil Gaiden": [2001, "Resident Evil Gaiden"],
"Main Hall - Resident Evil Gaiden": [2001, "Resident Evil Gaiden"],
"Class Cabin - Resident Evil Gaiden": [2001, "Resident Evil Gaiden"],
"Corridor - Resident Evil Gaiden": [2001, "Resident Evil Gaiden"],
"Introduction - Resident Evil Gaiden": [2001, "Resident Evil Gaiden"],
"Side Deck X - Resident Evil Gaiden": [2001, "Resident Evil Gaiden"],
"Restaurant - Resident Evil Gaiden": [2001, "Resident Evil Gaiden"],
"Corridor X - Resident Evil Gaiden": [2001, "Resident Evil Gaiden"],
  "Training Facility II - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Training Facility III - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Training Facility IV - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Training Facility Main Theme - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Tyrant, Again - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Uneasiness - Resident Evil Zero": [2002, "Resident Evil Zero"],
"ZERO - Resident Evil Zero": [2002, "Resident Evil Zero"],
"ZERO ver. 2 - Resident Evil Zero": [2002, "Resident Evil Zero"],
"ZOMBIE DOG - Resident Evil Zero": [2002, "Resident Evil Zero"],
"1st Zombie - Resident Evil Zero": [2002, "Resident Evil Zero"],
"A Flash - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Advertise - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Air Raid - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Assassin's Dagger - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Assault - Resident Evil Zero": [2002, "Resident Evil Zero"],
"BEGINNING - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Billy's Recollection - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Catch and Hang - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Centipede - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Chapel II - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Chapel III - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Chapel Main Theme - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Chess - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Confrontation With Marcus - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Countdown - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Critical Point - Resident Evil Zero": [2002, "Resident Evil Zero"],
"D-A-L-I - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Dormitory Chapel - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Dormitory Main Theme - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Dormitory Treatment Plant - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Doubt - Resident Evil Zero": [2002, "Resident Evil Zero"],
"ED ZOMBIE - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Encounter - Resident Evil Zero": [2002, "Resident Evil Zero"],
"END ROLL - Resident Evil Zero": [2002, "Resident Evil Zero"],
"ESCAPE - Resident Evil Zero": [2002, "Resident Evil Zero"],
"EX GAME - Resident Evil Zero": [2002, "Resident Evil Zero"],
"In the Cage Room - Resident Evil Zero": [2002, "Resident Evil Zero"],
"In the Torture Room - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Incubation - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Invitation - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Lament Failure - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Lament Success - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Last Whisper - Resident Evil Zero": [2002, "Resident Evil Zero"],
"LEECHMAN 1 - Resident Evil Zero": [2002, "Resident Evil Zero"],
"LEECHMAN 2 - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Lullaby 1 - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Lullaby 2 - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Marcus' Memories - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Marcus' Scheme - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Means of Escape - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Melting - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Mimesis - Resident Evil Zero": [2002, "Resident Evil Zero"],
"MISSION - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Nightmare - Resident Evil Zero": [2002, "Resident Evil Zero"],
"P Tyrant01 - Resident Evil Zero": [2002, "Resident Evil Zero"],
"P Tyrant02 - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Predator - Resident Evil Zero": [2002, "Resident Evil Zero"],
"QUEEN LEECH - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Rest - Resident Evil Zero": [2002, "Resident Evil Zero"],
"RESULT - Resident Evil Zero": [2002, "Resident Evil Zero"],
"SAVE REB - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Scorching Nightmare - Resident Evil Zero": [2002, "Resident Evil Zero"],
"SCP BATTLE - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Slaughter - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Spasm and Curve - Resident Evil Zero": [2002, "Resident Evil Zero"],
"Strange Clump - Resident Evil Zero": [2002, "Resident Evil Zero"],
"The Creeping Hiru 1 - Resident Evil Zero": [2002, "Resident Evil Zero"],
"The Creeping Hiru 2 - Resident Evil Zero": [2002, "Resident Evil Zero"],
"The Creeping Hiru 3 - Resident Evil Zero": [2002, "Resident Evil Zero"],
"To the Depths of Insanity - Resident Evil Zero": [2002, "Resident Evil Zero"],
    "Pursued and Hunted - Resident Evil Resistance": [2020, "Resident Evil Resistance"],
"Resistance (Downtempo Mix) - Resident Evil Resistance": [2020, "Resident Evil Resistance"],
"Resistance - Resident Evil Resistance": [2020, "Resident Evil Resistance"],
"Sick Diversions - Resident Evil Resistance": [2020, "Resident Evil Resistance"],
"Tear and Mutilate - Resident Evil Resistance": [2020, "Resident Evil Resistance"],
"The Carnivore - Resident Evil Resistance": [2020, "Resident Evil Resistance"],
"The Malformation of G (Resistance Mix) - Resident Evil Resistance": [2020, "Resident Evil Resistance"],
"The Pressure is on - Resident Evil Resistance": [2020, "Resident Evil Resistance"],
"Twisted Science - Resident Evil Resistance": [2020, "Resident Evil Resistance"],
"Black Impact (Resistance Mix)Mr. X Theme - Resident Evil Resistance": [2020, "Resident Evil Resistance"],
"Building Fear - Resident Evil Resistance": [2020, "Resident Evil Resistance"],
"Casino of Horrors - Resident Evil Resistance": [2020, "Resident Evil Resistance"],
"City of the Undead - Resident Evil Resistance": [2020, "Resident Evil Resistance"],
"Cruel Experiments - Resident Evil Resistance": [2020, "Resident Evil Resistance"],
"Descent Into Darkness - Resident Evil Resistance": [2020, "Resident Evil Resistance"],
"Downtown Panic - Resident Evil Resistance": [2020, "Resident Evil Resistance"],
"Final Countdown - Resident Evil Resistance": [2020, "Resident Evil Resistance"],
"Have You Survived - Resident Evil Resistance": [2020, "Resident Evil Resistance"],
"Laboratory Nightmares - Resident Evil Resistance": [2020, "Resident Evil Resistance"],
"Lair of Evil - Resident Evil Resistance": [2020, "Resident Evil Resistance"],

  


})

function createMetadata(mtd) {
    let m = {}
    for(const soundtrack in mtd) {
        m[soundtrack] = {
            'year': mtd[soundtrack][0],
            'game': mtd[soundtrack][1],
        }
    }
    return m
}
function _onSubmit() {
}

function appendMetadata(guess, row) {
    if (!guess.isCorrect) {
        let guessMeta = _metadata[guess.answer];
        let heardleMeta = _metadata[currentHeardle.correctAnswer];
        if (guessMeta && heardleMeta) {
          
            const metaEvaluation = document.createElement("div");
      metaEvaluation.style.maxWidth = "60%"
            metaEvaluation.innerHTML = `<div><div>Year: <span>${heardleMeta.year > guessMeta.year ? `Newer than ${guessMeta.year}.` : heardleMeta.year == guessMeta.year ? `${guessMeta.year} is correct!` : `Older than ${guessMeta.year}.`}</span></div>` +
            `<div>Game: <span>${heardleMeta.game == guessMeta.game ? `${guessMeta.game} is correct!` : `${guessMeta.game} is incorrect.`}</span></div>`
            row.appendChild(metaEvaluation);
        }
    }
}

function setCurrentHeardle(l) {
    currentHeardle = l; 
    setTimeout(() => {
        const rows = document.querySelectorAll("body > main > div.w-full.flex.flex-col.flex-grow.relative > div > div > div");
        stats = localStorage.getItem("userStats")
        if(stats != null ) {
            paresdStats = JSON.parse(stats)
            paresdStats.filter(p => p.correctAnswer == currentHeardle.correctAnswer)[0].guessList.forEach((guess, index) => {
                appendMetadata(guess, rows[index])
            })
        }
    }, 200)
}

function evaluateGuessMetadata(v) {
    const rows = document.querySelectorAll("body > main > div.w-full.flex.flex-col.flex-grow.relative > div > div > div");
    const last = v[v.length-1]
    appendMetadata(last, rows[v.length-1]);
}

let currentHeardle = null;
